# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20171125_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('facebook_email', models.CharField(max_length=200)),
                ('facebook_password', models.CharField(max_length=200)),
                ('interval_time', models.IntegerField(default=18000)),
                ('total_time', models.IntegerField(default=72000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.DeleteModel(
            name='Facebook_account',
        ),
        migrations.AddField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
