# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171125_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creation_date',
        ),
    ]
