# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_facebook_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interval_time',
            field=models.IntegerField(default=180),
        ),
    ]
