# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171128_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interval_time',
            field=models.IntegerField(default=240),
        ),
    ]
