# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171129_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
