# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redColor', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
