# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171205_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing', models.BooleanField(default=True)),
            ],
        ),
    ]
