# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_goon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='boardTemplateNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
