# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171214_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='beingSet',
            field=models.BooleanField(default=False),
        ),
    ]
